[package]
name = "goteira"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.32", features = ["full"] }
surge-ping = "0.8"
chrono = "0.4"
regex = "1.9"
anyhow = "1.0"
socket2 = "0.6.2"
rand = "0.10.0"
